before_install:
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get update
install:
  - sudo apt-get install texlive-full texlive
script:
  - pdflatex -synctex=1 -interaction=nonstopmode report.tex
#  - bibtex report.aux
#  - pdflatex -synctex=1 -interaction=nonstopmode report.tex 
#  - pdflatex -synctex=1 -interaction=nonstopmode report.tex
after-succeed:
  - mutt -a informe.pdf -s "[master-sce] Report compilation #$TRAVIS_BUILD_NUMBER succeeded" -- javierdo1@gmail.com gorkasantosortuzar@gmail.com < "La compilación ha ido bien"
notifications:
  email:
    recipients:
      - javierdo1@gmail.com
      - gorkasantosortuzar@gmail.com
    on_success: never
    on_failure: always
